import type { Configuration } from '../contract';
import defaults from './defaults.json';

/** `Configuration::default()` from Rust (macOS defaults), regenerated by the contract test. */
export function defaultConfiguration(): Configuration {
  return structuredClone(defaults.configuration) as Configuration;
}
