// Generated by crates/att-engine/tests/contract_ts.rs from the Rust contract types.
// Do not edit: run `npm run contract` in apps/desktop (or the cargo command in that
// file) after changing a Rust type. Instants are RFC 3339 strings, days `YYYY-MM-DD`.

export type ActivityType = { id: string; name?: string | null; color?: string | null };

export type AgendaEventView = {
  id: string;
  title: string;
  start: string;
  end: string;
  allDay: boolean;
  calendarTitle: string | null;
  color: string | null;
  location: string | null;
  isNow: boolean;
};

export type AgendaSlice = {
  /** Calendar integration exists on this OS. */
  supported: boolean;
  access: CalendarAccess;
  enabled: boolean;
  calendars: Array<CalendarChoice>;
  day: string;
  events: Array<AgendaEventView>;
  issue: string | null;
};

/** `ExplorerAnalysis` without its entry list (paged through `statistics.entries`). */
export type AnalysisView = {
  window: Interval;
  tasks: Array<ExplorerTask>;
  activities: Array<ExplorerActivity>;
  buckets: Array<ExplorerBucket>;
  weekdays: Array<ExplorerPattern>;
  hours: Array<ExplorerPattern>;
  lengths: Array<ExplorerPattern>;
  resolution: ExplorerResolution;
  total: number;
  covered: number;
  count: number;
  trackedDays: number;
  median: number;
  billable: number;
  billableKnownCount: number;
  target: number;
  context: ContextInsights;
  entryCount: number;
  /** The first entries, for the always-visible list (8 in 1.14.x). */
  entriesPreview: Array<ExplorerEntry>;
};

export type AppIdentity = {
  /** macOS bundle ID, or Windows executable file name in lower case. */
  id: string;
  name: string;
  path: string | null;
};

export type AppSlice = {
  version: string;
  os: HostOs;
  preview: boolean;
  /** Show the appearance onboarding instead of the app. */
  onboarding: boolean;
  visiblePage: string | null;
  /** Sidebar pages in order. */
  pages: Array<PageInfo>;
  /** A remote write or connection is in progress. */
  busy: boolean;
  notice: string | null;
  /** The latest error, shown in a dismissible banner. */
  error: string | null;
  storageIssue: string | null;
  features: Features;
};

export type AttentionView = {
  id: string;
  /** `activityCheck`, `timeLimit` or `activityTimeout`. */
  reason: string;
  heading: string;
  detail: string;
  ticketId: number | null;
  title: string;
  stopped: boolean;
};

/** One row of the App activity log. Persisted in `state.json` as `audit`, newest first. */
export type AuditEntry = { id: string; date: string; title: string; detail: string };

/**
 * A confirmed branch switch waiting for the user's decision. Persisted in `state.json` as
 * `pending`; reads the Swift keys `repositoryID` and `ticketID`.
 */
export type BranchChange = {
  id: string;
  repositoryId: string;
  repositoryName: string;
  branch: string;
  previousBranch?: string | null;
  ticketId?: number | null;
  detectedAt: string;
};

/**
 * The result of `settings.testBranchPattern`: the tester line and whether the pattern is
 * valid (`false` with "Invalid pattern: …").
 */
export type BranchPatternTest = { text: string; valid: boolean };

export type BranchPromptView = {
  change: BranchChange;
  ticketTitle: string | null;
  /** `develop` / `long-feature/*`: offer Pause, Stop or Keep. */
  suggestsBreak: boolean;
};

/** Polling intervals in seconds. The 7pace interval stays in `poll_seconds` for compatibility. */
export type Cadences = {
  /** Git HEAD, presence, microphone and Figma probes. */
  probeSeconds: number;
  calendarSeconds: number;
  progressSeconds: number;
  updateCheckSeconds: number;
};

export type CalendarAccess =
  | "notDetermined"
  | "denied"
  | "restricted"
  | "authorized"
  | "unsupported";

export type CalendarChoice = {
  selected: boolean;
  id: string;
  title: string;
  /** `#rrggbb`. */
  color: string | null;
  /** Account or source name, e.g. "iCloud" or an Exchange account. */
  source: string | null;
};

export type Configuration = {
  organization: string;
  project: string;
  sevenPaceUrl: string;
  sevenPaceAuthMode: SevenPaceAuthMode;
  repositories: Array<Repository>;
  branchPattern: string;
  autoStartWhenIdle: boolean;
  notificationsEnabled: boolean;
  watchEnabled: boolean;
  calendarEnabled: boolean;
  selectedCalendarIds: Array<string>;
  activityTypeId: string;
  pollSeconds: number;
  figma: FigmaPreferences;
  interface: InterfacePreferences;
  /**
   * `None` for settings saved before onboarding existed (see
   * `InterfacePreferences::needs_onboarding`).
   */
  interfaceSetupCompleted: boolean | null;
  microphone: MicrophonePreferences;
  meetings: MeetingPreferences;
  targets: WorkTargets;
  completionReminders: boolean;
  automaticUpdateChecks: boolean;
  quickSwitchEnabled: boolean;
  awareness: WorkAwarenessPreferences;
  dayReview: DayReviewPreferences;
  /** Per prompt kind; missing kinds use [`Interruption::default`]. */
  interruptions: { [key in PromptKind]?: Interruption };
  quietHours: QuietHours;
  cadences: Cadences;
  /** Page ids hidden from the sidebar (`offlineDrafts`, `weeklyReport`, …). */
  hiddenPages: Array<string>;
  /** Small always-on-top elapsed-time window (mainly for Windows). */
  miniTimer: boolean;
  /**
   * Quick-switch accelerator; `None` uses the OS default (⌃⌥T on macOS,
   * Ctrl+Alt+Shift+T on Windows).
   */
  quickSwitchShortcut: string | null;
};

export type ConnectionSlice = {
  health: Health;
  /** The tray/status icon state. */
  indicator: TrayState;
  /** One-line status, e.g. "7pace connected". */
  status: string;
  detail: string | null;
  /** Lower-cased workspace URL, empty when not configured. */
  workspace: string;
  host: string | null;
  /** Last confirmed 7pace timer read. */
  lastSync: string | null;
  /** Last successful worklog download for progress. */
  worklogSync: string | null;
  connectionIssue: string | null;
  azureIssue: string | null;
  progressIssue: string | null;
  hasAzurePat: boolean;
  hasSevenPaceToken: boolean;
  connected: boolean;
  connecting: boolean;
  /** Why the last ticket completion check failed ("Ticket completion check: …"). */
  completionIssue?: string | null;
  /**
   * The quick-switch shortcut could not be registered (reported by the shell through
   * `app.reportShortcutIssue`).
   */
  shortcutIssue?: string | null;
};

export type ContextDay = {
  /** The instant the local day starts. */
  date: string;
  switches: number;
  /** Durations of continuous same-context work, in order. */
  blocks: Array<number>;
};

export type ContextInsights = {
  days: Array<ContextDay>;
  /** Invalid logs plus every segment in an overlapping cluster. */
  ambiguousEntries: number;
};

/** Intents owned by the page controllers. Field names are camelCase on the wire. */
export type ControllerIntent =
  | { type: "statistics.setPeriod"; period: StatisticsPeriod }
  | { type: "statistics.move"; amount: number }
  | { type: "statistics.current" }
  | { type: "statistics.jumpTo"; date: string }
  | { type: "statistics.setFilter"; filter: ExplorerFilter }
  | { type: "statistics.clearFilters" }
  | { type: "statistics.zoomTo"; start: string; end: string }
  | { type: "statistics.scale"; factor: number }
  | { type: "statistics.pan"; direction: number }
  | { type: "statistics.back" }
  | { type: "statistics.resetZoom" }
  | { type: "statistics.setSection"; section: StatisticsSection }
  | { type: "statistics.refresh" }
  | {
      type: "statistics.entries";
      offset: number;
      limit: number;
      start?: string | null;
      end?: string | null;
    }
  | { type: "timeEditor.setDay"; day: string }
  | { type: "timeEditor.setFilter"; text: string }
  | { type: "timeEditor.load" }
  | { type: "timeEditor.select"; logId: string }
  | { type: "timeEditor.cancel" }
  | { type: "timeEditor.setMode"; mode: TimeEditMode }
  | { type: "timeEditor.setTimes"; start: string; end: string }
  | { type: "timeEditor.setSplit"; at: string; ticket: string; comment: string; activityId: string }
  | { type: "timeEditor.setSecondEntry"; ticket: string; comment: string; activityId: string }
  | { type: "timeEditor.setSelection"; ids: Array<string> }
  | { type: "timeEditor.beginMerge" }
  | { type: "timeEditor.beginUndo"; changeId: string }
  | { type: "timeEditor.checkOverlaps" }
  | { type: "timeEditor.save" }
  | { type: "timeEditor.acknowledge"; changeId: string }
  | { type: "timeEditor.showCorrections"; show: boolean }
  | { type: "timeEditor.loadCorrections" }
  | {
      type: "timeEditor.prepareCorrection";
      issueId: string;
      option: string;
      boundary?: string | null;
    }
  | { type: "timeEditor.setSeparateIdle"; separate: boolean }
  | { type: "dayReview.setDay"; day: string }
  | { type: "dayReview.refresh" }
  | { type: "weekly.move"; amount: number }
  | { type: "weekly.jumpTo"; date: string }
  | { type: "weekly.refresh" }
  | { type: "weekly.generate"; replace: boolean }
  | { type: "weekly.setText"; text: string }
  | { type: "weekly.exportMarkdown"; path: string }
  | {
      type: "offline.startLocal";
      ticketId: number | null;
      comment: string;
      activityId: string | null;
    }
  | { type: "offline.stopLocal" }
  | { type: "offline.save"; draft: OfflineDraft }
  | { type: "offline.remove"; draftId: string }
  | { type: "offline.review"; draftId: string }
  | { type: "offline.upload" }
  | { type: "offline.link"; logId: string }
  | { type: "offline.allowRetryAfterManualCheck" }
  | { type: "offline.setShowSynced"; show: boolean }
  | { type: "ticket.showContext"; ticketId: number }
  | { type: "ticket.closeContext" }
  | { type: "ticket.openInAzure"; ticketId: number };

/**
 * The corrections offered for one gap or overlap: `extendEarlier`, `startLaterEarlier` (gaps),
 * `removeFromEarlier`, `removeFromLater`, `boundary` (overlaps).
 */
export type CorrectionChoices = { issueId: string; options: Array<string> };

export type CorrectionsView = {
  show: boolean;
  issues: Array<TimeCorrectionIssue>;
  loading: boolean;
  issue: string | null;
  /**
   * For each of `issues`, in the same order: its id and the correction options with a valid
   * plan, for `timeEditor.prepareCorrection`.
   */
  choices: Array<CorrectionChoices>;
};

/** Persisted in the configuration as `endOfDayReview`. */
export type DayReviewPreferences = {
  enabled: boolean;
  /** Minutes after local midnight. */
  startMinute: number;
  finishMinute: number;
  /** Swift weekday numbers (1 = Sunday … 7 = Saturday). */
  weekdays: Array<number>;
  longSessionMinutes: number;
  gapMinutes: number;
};

export type DayReviewPromptView = { day: string; canSnooze: boolean };

/** Persisted per workspace and local day under [`DayReviewSchedule::key`]. */
export type DayReviewRecord = {
  promptedAt?: string | null;
  snoozedUntil?: string | null;
  reviewedAt?: string | null;
};

export type DayReviewSlice = {
  selectedDay: string;
  summary: DayReviewSummary | null;
  record: DayReviewRecord | null;
  /** The scheduled target for the day. */
  targetSeconds: number;
  longEntryMinutes: number;
  loading: boolean;
  issue: string | null;
  syncedAt: string | null;
  /** The shortest gap the review reports, in minutes (Day review preferences). */
  gapMinutes: number;
  /** A 7pace connection exists ("Refresh review" is available). */
  configured: boolean;
};

export type DayReviewSummary = {
  /** The instant the local day starts. */
  day: string;
  /** Clipped to the day and to `now`, sorted by start, then ID. */
  sessions: Array<ReviewSession>;
  gaps: Array<ReviewGap>;
  omittedLogs: number;
  gapsUnavailable: boolean;
  timerRunning: boolean;
  timerUnconfirmed: boolean;
};

export type DiscoveredView = { path: string; branch: string; alreadyAdded: boolean };

/** Where a draft came from; decides labels and revalidation. */
export type DraftSource =
  | "ticket"
  | "branch"
  | "meeting"
  | "microphone"
  | "figma"
  | "resume"
  | "attention"
  | "meetingReturn"
  | "manual";

export type DraftView = {
  id: string;
  source: DraftSource;
  title: string;
  item: WorkItem | null;
  /** "Use Azure ticket" can be switched off. */
  allowsNoTicket: boolean;
  manual: ManualTrackingKind | null;
  /**
   * The activity the chooser preselects (Swift `preferredActivityID`), or `""` when that
   * activity is not loaded.
   */
  preferredActivityId: string;
  /** Activities the user may start with; empty means any loaded activity. */
  allowedActivityIds: Array<string>;
  /** Shown when an activity is required but missing (Design for Figma, Standup for stand-ups). */
  requiredActivity: string | null;
  /** Prefilled comment for ticket-free starts. */
  defaultComment: string;
  /** The primary button says "Resume" instead of "Start". */
  resume: boolean;
  /** A daily stand-up: only the Standup activity can start it. */
  standup: boolean;
  /** Started from Figma: only the Design activity can start it. */
  isFigma: boolean;
  /** The 7pace comment the draft carries (Swift `remark`), shown with the ticket switched off. */
  remark: string | null;
  /** "Comment: …" with the ticket included (Swift `trackingComment(includeTicket: true)`). */
  commentWithTicket: string | null;
  /** "Comment: …" with the ticket switched off. */
  commentWithoutTicket: string | null;
  /** The calendar meeting the draft is for. */
  meetingTitle: string | null;
  /**
   * "Choose a ticket instead…" / "Choose another ticket…" is offered
   * (`tracking.chooseSuggestionTicket`).
   */
  canChooseTicket: boolean;
  /**
   * The activity ids `tracking.start` accepts right now (Swift `canStart`), `""` included
   * when the workspace has no activity types; empty while busy or disconnected.
   */
  startableActivityIds: Array<string>;
};

/** One page of explorer entries (result of `statistics.entries`). */
export type EntriesPage = { offset: number; total: number; entries: Array<ExplorerEntry> };

export type ExplorerActivity = { id: string; name: string; seconds: number };

export type ExplorerBucket = {
  start: string;
  end: string;
  /** Stacked by activity ID. */
  segments: Array<ExplorerSegment>;
};

/** One cell of the Monday-first ISO calendar heatmap. */
export type ExplorerCalendarDay = {
  /** The instant the local day starts. */
  date: string;
  /** The part of the day inside the window. */
  interval: Interval;
  seconds: number;
  /** Distinct worklogs. */
  entries: number;
  target: number;
  /** Column: ISO weeks since the week containing the window start. */
  week: number;
  /** Row: Monday = 0 … Sunday = 6. */
  weekday: number;
  future: boolean;
};

/** The part of a record inside the window and inside one local day. */
export type ExplorerEntry = { record: ExplorerRecord; start: string; end: string };

export type ExplorerFilter = {
  /** Case- and diacritic-insensitive search in ticket number, title, comment and activity. */
  query: string;
  activityId: string | null;
  taskId: string | null;
  /** Swift weekday number (1 = Sunday … 7 = Saturday), matched per day segment. */
  weekday: number | null;
  /** Index into [`ExplorerRecord::BAND_NAMES`], matched on the original log length. */
  lengthBand: number | null;
};

/** One cell of the hourly grid. */
export type ExplorerHeatHour = {
  interval: Interval;
  /** The start of the cell's local day. */
  day: string;
  seconds: number;
  /** Chronological hour since the day started, so a repeated DST hour is a separate slot. */
  slot: number;
};

export type ExplorerPattern = {
  /** Swift weekday number, hour of day or length band, depending on the list. */
  id: number;
  label: string;
  seconds: number;
  /** Weekdays: days of that weekday up to now; lengths: distinct worklogs; hours: 0. */
  count: number;
};

export type ExplorerProgressPoint = { date: string; seconds: number; target: number };

/** A parsed worklog. */
export type ExplorerRecord = {
  log: WorkLog;
  start: string;
  end: string;
  /** `ticket:<id>`, or `free:<utf8 length of activity ID>:<activity ID><comment>`. */
  taskId: string;
  ticketId: number | null;
  /** `activity:<id>`, or `unspecified`. */
  activityId: string;
  activityName: string;
};

/** Bucket size of the time chart. Serialized as the Swift raw value, which is also the label. */
export type ExplorerResolution = "Monthly" | "Daily" | "Hourly" | "15 minutes" | "5 minutes";

/** One activity's slice of a stacked bucket. */
export type ExplorerSegment = { activityId: string; name: string; bottom: number; top: number };

export type ExplorerTask = {
  id: string;
  ticketId: number | null;
  title: string;
  seconds: number;
  /** Distinct worklogs. */
  count: number;
  /** Distinct local days. */
  days: number;
  lastWorked: string;
};

export type ExplorerVisuals = {
  days: Array<ExplorerCalendarDay>;
  /** Empty for windows longer than eight days. */
  hours: Array<ExplorerHeatHour>;
  /** Cumulative recorded time per bucket, up to `max(now, last entry end)`. */
  progress: Array<ExplorerProgressPoint>;
  /** Cumulative target at the end of each day. */
  targetProgress: Array<ExplorerProgressPoint>;
  weekCount: number;
};

export type Features = {
  /** Calendar integration exists on this OS (macOS only at launch). */
  calendar: boolean;
  /** The microphone probe works on this OS version. */
  microphone: boolean;
  /** Figma files are identified by window title only (Windows, experimental). */
  figmaTitleOnly: boolean;
};

/** One activation in the history. */
export type FigmaContextEvent = {
  id: string;
  timestamp: string;
  kind: string;
  file: string;
  name: string;
  ticketId?: number | null;
};

export type FigmaFileView = {
  key: string;
  name: string;
  /** `https://www.figma.com/file/<key>`, `None` for title-only files. */
  webUrl: string | null;
  desktopUrl: string | null;
  ticketId: number | null;
  ticketTitle: string | null;
  lastSeen: string | null;
};

/** Figma context settings. Persisted as `Configuration.figmaDetection`. */
export type FigmaPreferences = {
  enabled: boolean;
  /** "Keep tracking" hides a suggestion for this long (0–120; 0 hides nothing). */
  dismissalMinutes: number;
  /** History retention (1–365). */
  historyDays: number;
};

export type FigmaPromptView = { suggestion: FigmaSuggestion; ticketTitle: string | null };

export type FigmaSlice = {
  preferences: FigmaPreferences;
  access: boolean;
  installed: boolean;
  titleOnly: boolean;
  /** Last observation: `missingAccess`, `waiting`, `noAddress`, `file` or `notForeground`. */
  status: string;
  currentFile: string | null;
  search: string;
  files: Array<FigmaFileView>;
  suggestions: Array<FigmaPromptView>;
  /** The most recently worked linked ticket and its files. */
  lastWorkedTicket: number | null;
  /** Newest first, at most 200. */
  history: Array<FigmaContextEvent>;
  storageIssue: string | null;
  /** Observation is on (`preferences.enabled`) and not paused by "Pause watching". */
  observing: boolean;
  /** The status line (Swift `FigmaService.status`, without the time). */
  label: string;
  /**
   * When Figma was last in front, and the file seen then ("Waiting for Figma · 10:02 ·
   * Seen: …").
   */
  lastForegroundAt: string | null;
  /** The files linked to `lastWorkedTicket`, most recently seen first. */
  lastWorked: Array<FigmaFileView>;
  /** History events in total (the list shows the latest 200). */
  historyCount: number;
};

/** "Start Design for this file?" */
export type FigmaSuggestion = {
  id: string;
  file: string;
  name: string;
  ticketId?: number | null;
  created: string;
};

export type FlowSlice = {
  surface: FlowSurface;
  draft: DraftView | null;
  /** A branch, meeting or Figma suggestion the user is choosing a ticket for. */
  selectedSuggestion: SuggestionView | null;
  search: SearchView;
  activityTypes: Array<ActivityType>;
  activitiesLoaded: boolean;
  loadingActivities: boolean;
  activityError: string | null;
  /** Favourites first, then recent tickets (Swift `QuickTickets.orderedIDs`). */
  quickTickets: Array<QuickTicketView>;
  defaultActivityId: string;
};

export type FlowSurface = "none" | "panel" | "picker";

/** "Working without a timer?" */
export type ForgottenReminder = { id: string; since: string; appName: string };

export type ForgottenTicketView = { repository: string; ticketId: number; title: string | null };

/** Intents handled by the engine itself. */
export type GenericIntent =
  | { type: "app.snapshot" }
  | { type: "app.setVisiblePage"; page: string | null };

export type Health =
  | "unconfigured"
  | "connecting"
  | "confirmed"
  | "stale"
  | "disconnected"
  | "authentication"
  | "accessDenied";

export type HistorySlice = {
  from: string;
  to: string;
  /** Newest first. */
  logs: Array<WorkLog>;
  todayLogs: Array<WorkLog>;
  loading: boolean;
  loaded: boolean;
  totalSeconds: number;
  /** App activity, newest first (at most 2,000). */
  audit: Array<AuditEntry>;
  /** Why the last load or CSV export failed (1.14.x showed it in the error banner). */
  issue?: string | null;
};

/** The operating system, for per-OS defaults such as work apps and microphone apps. */
export type HostOs = "macos" | "windows" | "other";

/** Detected time away from the running timer. */
export type IdlePeriod = {
  id: string;
  session: IdleTrackingSession;
  start: string;
  end?: string | null;
  reason: string;
};

/** The confirmed running timer that idle evidence belongs to. */
export type IdleTrackingSession = {
  identity: string;
  workLogId: string;
  title: string;
  start: string;
};

export type InterfaceContrast = "system" | "standard" | "increased";

/**
 * Appearance settings. Persisted as `Configuration.interfacePreferences`.
 *
 * Decoding never fails: unsupported future values, wrong types and non-objects fall back to
 * the defaults field by field, so they cannot prevent loading account and tracking settings.
 */
export type InterfacePreferences = {
  theme: InterfaceTheme;
  /** Percent, serialized as the raw number (`InterfaceScale::ALL`). */
  scale: 90 | 100 | 110 | 125 | 150;
  contrast: InterfaceContrast;
};

export type InterfaceTheme = "system" | "light" | "dark";

/**
 * How strongly a new prompt may interrupt. 1.14.x always opened the panel and took focus
 * (`OpenAndFocus`); 2.0 opens the panel without stealing focus by default.
 */
export type Interruption = "off" | "notifyOnly" | "openPanel" | "openAndFocus";

export type InterruptionChoice = { kind: PromptKind; label: string; level: Interruption };

/** A half-open interval `[start, end)`. */
export type Interval = { start: string; end: string };

/** `{ kind, message }`. `kind` is stable for UI logic; `message` is shown to the user verbatim. */
export type IpcError = { kind: string; message: string };

export type LocalTimerView = {
  draftId: string;
  ticketId: number | null;
  title: string;
  comment: string | null;
  activityName: string | null;
  start: string;
  /** The timer belongs to another 7pace workspace ("Workspace: …"). */
  otherWorkspace?: string | null;
};

/** What the user tracks without an Azure ticket (Swift `ManualTrackingKind`). */
export type ManualTrackingKind = "activity" | "meeting" | "standup";

/** One calendar occurrence, as the calendar probe reports it. */
export type MeetingEvent = {
  /** Identifies one occurrence, so a recurring meeting can prompt again the next day. */
  id: string;
  title: string;
  start: string;
  end: string;
  calendar: string;
  ticketId: number | null;
  allDay: boolean;
  cancelled: boolean;
  declined: boolean;
  free: boolean;
};

/** Meeting suggestion settings. Persisted as `Configuration.meetingSuggestions`. */
export type MeetingPreferences = {
  enabled: boolean;
  /** Ticket used when the meeting itself names none (free text, trimmed when used). */
  defaultTicket: string;
  activityTypeId: string;
};

export type MeetingPromptView = {
  event: MeetingEvent;
  /** The ticket a start would use (marker, work-item link or default meeting ticket). */
  ticketId: number | null;
};

export type MeetingReturnView = {
  ticketId: number;
  title: string | null;
  activityName: string | null;
  end: string;
  /** Due now: offer "Resume previous…". */
  ready: boolean;
  /** The meeting was a microphone session ("Microphone use stopped"). */
  fromMicrophone: boolean;
};

/** App categories the user can watch. Persisted by display name (`"Microsoft Teams"`). */
export type MicrophoneApp =
  | "Slack"
  | "Microsoft Teams"
  | "Zoom"
  | "Web browsers"
  | "Webex"
  | "Discord"
  | "FaceTime"
  | "Other apps";

export type MicrophoneDiagnostics = {
  supported: boolean;
  /** Every process with input running at the last sample. */
  owners: Array<MicrophoneOwnerView>;
  /** The last sample succeeded recently. */
  fresh: boolean;
  issue: string | null;
  /**
   * The status line ("Watching microphone status · checked every 2 seconds", "Microphone in
   * use: Slack", the last error, …).
   */
  status?: string | null;
  /** The last successful sample ("Checked 10:02:14"). */
  checkedAt?: string | null;
};

/** "Has your meeting finished?" for the timer that was running during the call. */
export type MicrophoneEndPrompt = {
  id: string;
  workspace: string;
  trackingIdentity: string;
  appNames: Array<string>;
  endedAt: string;
  notified: boolean;
};

/** An app using microphone input. */
export type MicrophoneOwner = {
  /** Bundle ID (macOS) or executable file name (Windows). */
  id: string;
  name: string;
};

/**
 * A process using microphone input and its app category (Settings shows "Selected" when the
 * category is watched, else "Ignored").
 */
export type MicrophoneOwnerView = {
  category: MicrophoneApp | null;
  /**
   * macOS: the owning app's bundle ID (WebKit helpers keep `com.apple.WebKit…`).
   * Windows: the executable file name in lower case, e.g. `ms-teams.exe`. Packaged (Store)
   * apps without a known mapping arrive as their package family name, `Name_PublisherId`.
   */
  id: string;
  /** Display name, e.g. "Microsoft Teams". */
  name: string;
  pid: number | null;
  path: string | null;
};

/** Microphone suggestion settings. Persisted as `Configuration.microphoneMeetings`. */
export type MicrophonePreferences = {
  enabled: boolean;
  /** Stored as raw display names. Unknown names are skipped instead of failing the settings. */
  apps: Array<MicrophoneApp>;
};

/** One continuous episode of input use by one app. */
export type MicrophoneSession = { id: string; owner: MicrophoneOwner; started: string };

/** Locally recorded time, possibly still running. Ported from `OfflineDraft`. */
export type OfflineDraft = {
  id: string;
  /** The workspace identity (lower-cased 7pace URL) the draft belongs to. */
  workspace: string;
  start: string;
  /** `None` while the local timer runs. */
  end?: string | null;
  ticketId?: number | null;
  comment: string;
  activityId?: string | null;
  billable: boolean;
  status: OfflineDraftStatus;
  /** The 7pace worklog ID once synced or linked. */
  remoteId?: string | null;
};

/** Upload state of a draft. Serializes as the Swift raw values. */
export type OfflineDraftStatus = "Local draft" | "Check 7pace before retrying" | "Synced to 7pace";

/** A stopped draft checked against 7pace before upload. Ported from `OfflineReview`. */
export type OfflineReview = {
  draft: OfflineDraft;
  /** Advisory overlaps; they never block an upload by themselves. */
  conflicts: Array<WorkLogConflict>;
  /** Why the overlap check is incomplete. */
  overlapIssue: string | null;
  /** Existing entries identical to the draft's proposal (link one instead of uploading). */
  matches: Array<WorkLog>;
};

export type OfflineSlice = {
  workspace: string;
  /** This workspace's drafts, newest first (synced ones only when `show_synced`). */
  drafts: Array<OfflineDraft>;
  showSynced: boolean;
  active: OfflineDraft | null;
  readyCount: number;
  /** Cached activity types for offline entry. */
  activities: Array<ActivityType>;
  review: OfflineReview | null;
  working: boolean;
  issue: string | null;
  message: string | null;
  canCreate: boolean;
  /** A 7pace connection exists (reviews and uploads are available). */
  configured: boolean;
};

export type PageInfo = {
  id: string;
  title: string;
  /** `today`, `insights` or `setup`. */
  group: string;
  /** Hidden by the user (Settings → Features). */
  hidden: boolean;
  /** Unavailable on this OS (Agenda on Windows). */
  available: boolean;
  /** A count shown on the item, e.g. pending branch changes on Overview. */
  badge: number | null;
  /** A dot shown on the item, e.g. a due day review. */
  dot: boolean;
};

export type PairingView = {
  pin: string | null;
  expiresAt: string | null;
  status: string | null;
  pairedHost: string | null;
  busy: boolean;
};

export type PausedView = {
  ticketId: number | null;
  title: string;
  activityId: string | null;
  activityName: string | null;
  remark: string | null;
  pausedAt: string;
  elapsedSeconds: number;
};

/**
 * Today and this-week progress toward the targets, computed at `computed_at`. While
 * `extrapolate` is true and a timer runs, the UI adds `now - computed_at` to both totals.
 */
export type ProgressSlice = {
  /** False until the week's worklogs loaded (UI shows "unavailable", never a misleading 0). */
  available: boolean;
  todaySeconds: number;
  weekSeconds: number;
  todayTarget: number;
  weekTarget: number;
  computedAt: string | null;
  extrapolate: boolean;
  /** Totals are older than the last tracking change (shown as "last known"). */
  stale: boolean;
  loading: boolean;
  issue: string | null;
  /**
   * Start of today: the UI extrapolates today's total from `max(computedAt, todayStart)`,
   * so a timer running across midnight counts only today's part.
   */
  todayStart?: string | null;
  /** Start of the ISO week (Monday), likewise for the week's total. */
  weekStart?: string | null;
  /** Why today's target differs (a holiday or a date exception). */
  todayReason?: string | null;
};

/** Every kind of prompt that can interrupt. */
export type PromptKind =
  | "branch"
  | "meeting"
  | "microphone"
  | "microphoneEnd"
  | "meetingReturn"
  | "figma"
  | "idle"
  | "forgottenTimer"
  | "ticketCompletion"
  | "trackingAttention"
  | "dayReview"
  | "update";

export type PromptsSlice = {
  branches: Array<BranchPromptView>;
  meetings: Array<MeetingPromptView>;
  microphone: Array<MicrophoneSession>;
  microphoneEnd: MicrophoneEndPrompt | null;
  /** The microphone end prompt may offer "Resume previous ticket…". */
  canReturnAfterMicrophone: boolean;
  meetingReturn: MeetingReturnView | null;
  figma: Array<FigmaPromptView>;
  idle: IdlePeriod | null;
  /** A saved "Pause & review" correction waiting to be applied or discarded. */
  idleCorrection: IdlePeriod | null;
  forgotten: ForgottenReminder | null;
  forgottenTickets: Array<ForgottenTicketView>;
  ticketCompletion: TicketCompletionPrompt | null;
  dayReview: DayReviewPromptView | null;
};

export type QuickTicketView = { ticketId: number; title: string | null; favorite: boolean };

/**
 * While active, prompts do not open the panel or send notifications. They stay listed in the
 * panel and overview. 7pace activity checks still interrupt, because 7pace stops the timer
 * when they go unanswered.
 */
export type QuietHours = {
  enabled: boolean;
  /** Minutes after local midnight. */
  startMinute: number;
  endMinute: number;
};

export type RepositoriesSlice = {
  watching: boolean;
  repositories: Array<RepositoryView>;
  scan: ScanView;
};

export type Repository = { id: string; path: string; enabled: boolean };

export type RepositoryView = {
  id: string;
  path: string;
  name: string;
  enabled: boolean;
  branch: string | null;
  detached: boolean;
  error: string | null;
};

export type ReviewGap = { start: string; end: string };

export type ReviewSession = {
  id: string;
  start: string;
  end: string;
  ticketId: number | null;
  title: string;
  activity: string;
  isRunning: boolean;
  /** Judged on the original length, not the clipped part. */
  isLong: boolean;
};

export type ScanView = {
  scanning: boolean;
  root: string | null;
  results: Array<DiscoveredView>;
  unreadable: Array<string>;
  error: string | null;
};

export type SearchView = {
  query: string;
  results: Array<WorkItem>;
  searching: boolean;
  error: string | null;
};

/**
 * Intents owned by the session. Field names are camelCase on the wire.
 *
 * Where an action can happen in the tray panel or in the main window's ticket picker, it acts
 * in the surface that is open (see [`view::FlowSurface`]): the prompt actions `branch.track`,
 * `branch.chooseAnother`, `completion.switch` and `tracking.resume` use the picker while it is
 * open (`tracking.openPicker`) and otherwise open the panel flow; `tracking.chooseTicket`,
 * `tracking.chooseManual` and `tracking.continueWithoutTicket` use the panel while its flow is
 * open (`tracking.beginPanel`) and otherwise the picker. Meeting, microphone, Figma, meeting
 * return, forgotten-timer and attention actions always use the panel, as in 1.14.x.
 */
export type SessionIntent =
  | { type: "app.finishOnboarding" }
  | { type: "app.setInterface"; preferences: InterfacePreferences }
  | { type: "app.prepareForRestart" }
  | { type: "app.dismissError" }
  | { type: "app.dismissNotice" }
  | { type: "app.reportShortcutIssue"; issue?: string | null }
  | { type: "connection.retry" }
  | { type: "connection.refresh" }
  | { type: "connection.recheck" }
  | {
      type: "settings.save";
      configuration: Configuration;
      azurePat: string;
      sevenPaceToken: string;
    }
  | { type: "settings.enableCalendar" }
  | { type: "settings.setPromptInterruption"; kind: PromptKind; level: Interruption }
  | { type: "settings.setQuietHours"; quietHours: QuietHours }
  | { type: "settings.testBranchPattern"; branch: string; pattern: string }
  | { type: "settings.resolveWorkApp"; path: string }
  | { type: "app.reportNotificationPermission"; authorized: boolean }
  | { type: "pairing.generatePin"; workspace?: string | null }
  | { type: "pairing.cancel" }
  | { type: "repositories.scan"; path: string }
  | { type: "repositories.cancelScan" }
  | { type: "repositories.add"; paths: Array<string> }
  | { type: "repositories.setEnabled"; id: string; enabled: boolean }
  | { type: "repositories.remove"; id: string }
  | { type: "repositories.toggleWatching" }
  | { type: "branch.keep"; id: string }
  | {
      type: "branch.track";
      id: string;
      /** Where the user clicked; absent: the open surface (see the enum docs). */
      surface?: FlowSurface | null;
    }
  | { type: "branch.chooseAnother"; id: string; surface?: FlowSurface | null }
  | { type: "branch.pause"; id: string }
  | { type: "branch.stop"; id: string }
  | { type: "tracking.beginPanel"; branchId: string | null }
  | { type: "tracking.cancelPanel" }
  | { type: "tracking.openPicker" }
  | { type: "tracking.closePicker" }
  | { type: "tracking.search"; query: string }
  | { type: "tracking.chooseTicket"; ticketId: number; surface?: FlowSurface | null }
  | { type: "tracking.chooseManual"; kind: ManualTrackingKind }
  | { type: "tracking.chooseDifferentWork" }
  | { type: "tracking.chooseSuggestionTicket"; draftId: string }
  | { type: "tracking.continueWithoutTicket" }
  | {
      type: "tracking.start";
      draftId: string;
      activityId: string;
      comment: string;
      includeTicket: boolean;
    }
  | { type: "tracking.stop" }
  | { type: "tracking.pause" }
  | { type: "tracking.resume"; surface?: FlowSurface | null }
  | { type: "tracking.discardPause" }
  | { type: "tracking.confirmActivity" }
  | { type: "tracking.reloadActivities" }
  | { type: "attention.keepStopped" }
  | { type: "attention.continue" }
  | { type: "quick.switch" }
  | { type: "quick.toggleFavorite"; ticketId: number }
  | { type: "completion.keep" }
  | { type: "completion.stop" }
  | { type: "completion.switch"; surface?: FlowSurface | null }
  | { type: "meeting.begin"; id: string; useSuggestedTicket: boolean }
  | { type: "meeting.dismiss"; id: string }
  | { type: "meeting.returnResume" }
  | { type: "meeting.returnDismiss" }
  | { type: "microphone.choose"; sessionId: string; standup: boolean }
  | { type: "microphone.dismiss"; sessionId: string }
  | { type: "microphone.endKeep" }
  | { type: "microphone.endPause" }
  | { type: "microphone.endStop" }
  | { type: "microphone.checkNow" }
  | { type: "awareness.keepIdle" }
  | { type: "awareness.reviewIdle"; promptId: string }
  | { type: "awareness.openCorrection" }
  | { type: "awareness.discardCorrection" }
  | { type: "awareness.deferForgotten"; untilTomorrow: boolean }
  | { type: "awareness.chooseForgottenTicket"; ticketId: number | null }
  | { type: "dayReview.open" }
  | { type: "dayReview.markReviewed"; day: string }
  | { type: "dayReview.snooze" }
  | { type: "history.setRange"; from: string; to: string }
  | { type: "history.load" }
  | { type: "history.exportCsv"; path: string }
  | { type: "agenda.setDay"; day: string }
  | { type: "agenda.openCalendar" }
  | { type: "figma.setPreferences"; preferences: FigmaPreferences }
  | { type: "figma.requestAccess" }
  | { type: "figma.refreshAccess" }
  | { type: "figma.keep"; suggestionId: string }
  | { type: "figma.track"; suggestionId: string; useLinkedTicket: boolean }
  | { type: "figma.link"; fileKey: string; ticketId: number | null }
  | { type: "figma.unlink"; fileKey: string }
  | { type: "figma.open"; fileKey: string; desktop: boolean }
  | { type: "figma.clearHistory" }
  | { type: "figma.setSearch"; query: string };

export type SettingsSlice = {
  configuration: Configuration;
  hasAzurePat: boolean;
  hasSevenPaceToken: boolean;
  pairing: PairingView;
  microphone: MicrophoneDiagnostics;
  interruptions: Array<InterruptionChoice>;
  /** The last successful `settings.save` (a failure leaves it and shows `app.error`). */
  savedAt?: string | null;
  /**
   * Whether the OS allows notifications (reported by the shell through
   * `app.reportNotificationPermission`); `null` until known.
   */
  notificationsAuthorized?: boolean | null;
};

/**
 * How the app signs in to 7pace. Ported from `SevenPaceAuthMode`; a missing value means
 * `apiToken`, as in 1.14.x.
 */
export type SevenPaceAuthMode = "apiToken" | "mobilePIN";

export type StatisticsPeriod = "day" | "week" | "month" | "year";

/** A calendar day, Monday-first ISO week, month or year. Build it with [`StatisticsRange::new`]. */
export type StatisticsRange = { period: StatisticsPeriod; start: string; end: string };

/** The three Statistics sections. */
export type StatisticsSection = "time" | "tasks" | "patterns";

export type StatisticsSlice = {
  period: StatisticsPeriod;
  range: StatisticsRange;
  /** The downloaded period. */
  bounds: Interval;
  /** The zoomed window (equals `bounds` when not zoomed). */
  window: Interval;
  isZoomed: boolean;
  /** Steps available for "Back". */
  zoomDepth: number;
  filter: ExplorerFilter;
  section: StatisticsSection;
  loading: boolean;
  analyzing: boolean;
  issue: string | null;
  syncedAt: string | null;
  /** Invalid worklogs left out of every total. */
  omitted: number;
  availableActivities: Array<ExplorerActivity>;
  analysis: AnalysisView | null;
  visuals: ExplorerVisuals | null;
  /** Targets are compared only for the complete, unfiltered period. */
  targetComparable: boolean;
  /** A 7pace connection exists ("Refresh" is available). */
  configured: boolean;
};

export type SuggestionView = {
  /** `branch`, `meeting` or `figma`. */
  kind: string;
  title: string;
  ticketId: number | null;
};

/** A date whose target differs from the weekly schedule. */
export type TargetException = {
  /** Gregorian `yyyy-MM-dd` in the user's local time zone. */
  id: string;
  kind: TargetExceptionKind;
  /** Target hours for [`TargetExceptionKind::Custom`]. */
  hours: number;
  note: string;
};

/** Persisted as the exact Swift raw values. */
export type TargetExceptionKind =
  | "Full-day leave"
  | "Half-day leave"
  | "Replacement holiday"
  | "Custom target";

/** "This ticket is completed in Azure. Stop tracking?" */
export type TicketCompletionPrompt = {
  id: string;
  scope: string;
  trackingIdentity: string;
  ticketId: number;
  title: string;
  workflowState: string;
  notified: boolean;
};

/** Ticket details for the context panel. Missing text fields are empty strings, as in Swift. */
export type TicketContext = {
  id: number;
  title: string;
  state: string;
  type: string;
  assignedTo: string;
  project: string;
  iteration: string;
  tags: string;
  /** `System.Description` as plain text. */
  description: string;
  /** `Microsoft.VSTS.Common.AcceptanceCriteria` as plain text. */
  acceptanceCriteria: string;
  links: Array<TicketLink>;
};

export type TicketContextSlice = {
  /** The ticket whose panel is open. */
  ticketId: number | null;
  details: TicketContext | null;
  loading: boolean;
  issue: string | null;
  azureUrl: string | null;
};

/** A related link shown in the context panel. */
export type TicketLink = { title: string; url: string };

/** A gap between recorded time, or time recorded twice. Ported from `TimeCorrectionIssue`. */
export type TimeCorrectionIssue = {
  kind: TimeCorrectionKind;
  start: string;
  end: string;
  /** The entry before a gap, or the earlier of two overlapping entries. */
  earlier: WorkLog | null;
  /** The entry after a gap, or the later of two overlapping entries. */
  later: WorkLog | null;
};

/** Swift `TimeCorrectionIssue.Kind`. */
export type TimeCorrectionKind = "gap" | "overlap";

/** Swift `TimeEditMode`. */
export type TimeEditMode = "guided" | "edit" | "split" | "merge" | "undo";

export type TimeEditorSlice = {
  day: string;
  filter: string;
  /** The day's entries after the filter, newest first. */
  logs: Array<WorkLog>;
  /** The running entry, which cannot be edited. */
  runningLogId: string | null;
  selection: Array<string>;
  selected: WorkLog | null;
  mode: TimeEditMode;
  start: string | null;
  end: string | null;
  splitAt: string | null;
  secondTicket: string;
  secondComment: string;
  secondActivity: string;
  mergeLogs: Array<WorkLog>;
  undoRecord: WorkLogChange | null;
  /** The before/after preview of the pending change. */
  plan: WorkLogPlan | null;
  validationIssue: string | null;
  review: WorkLogEditReview | null;
  loading: boolean;
  working: boolean;
  issue: string | null;
  message: string | null;
  savedConflicts: Array<WorkLogConflict>;
  savedOverlapIssue: string | null;
  /** Recent edits for this workspace, newest first. */
  changes: Array<WorkLogChange>;
  requiresReview: boolean;
  journalIssue: string | null;
  needsReload: boolean;
  corrections: CorrectionsView;
  guidedPlan: WorkLogPlan | null;
  idleInterval: Interval | null;
  separateIdle: boolean;
  /** A 7pace connection exists. */
  configured: boolean;
  /**
   * Overlaps of the pending change with the loaded day's entries and the running timer,
   * shown before the optional full check (Swift `loadedConflicts`).
   */
  loadedConflicts: Array<WorkLogConflict>;
};

export type TrackingSlice = {
  running: boolean;
  ticketId: number | null;
  /** Ticket title, comment or "Unassigned time". */
  title: string;
  activityId: string | null;
  activityName: string | null;
  remark: string | null;
  /**
   * Elapsed seconds at `confirmed_at`. While `extrapolate` is true the UI adds
   * `now - confirmed_at`; otherwise the value stays still (stale or paused).
   */
  elapsedBase: number;
  confirmedAt: string | null;
  extrapolate: boolean;
  paused: PausedView | null;
  /** The running offline/local timer, if any. */
  local: LocalTimerView | null;
  /** The local timer leads the menu bar (Swift `showsLocalTimer`). */
  showsLocalTimer: boolean;
  /** The Azure/7pace session stays visible next to the local timer (Swift `showsRemoteTimer`). */
  showsRemoteTimer: boolean;
  attention: AttentionView | null;
  /** Seconds recorded today excluding the running entry (Swift `todaySeconds`). */
  todaySeconds: number;
  /** Azure web link for the running ticket, when the organization is configured. */
  ticketUrl: string | null;
};

/** The status icon vocabulary from 1.14.x (`TrackingIndicator`). */
export type TrayState =
  | "running"
  | "paused"
  | "stopped"
  | "disconnected"
  | "connecting"
  | "attention";

export type WeeklySlice = {
  range: StatisticsRange;
  text: string;
  /** Worklogs for this week are loaded. */
  hasData: boolean;
  /** A saved draft exists (regenerating asks first). */
  hasDraft: boolean;
  loading: boolean;
  issue: string | null;
  storageIssue: string | null;
  message: string | null;
  syncedAt: string | null;
  /** A 7pace connection exists (drafts are saved per workspace). */
  configured: boolean;
  /** The file name the export dialog suggests: `weekly-status-<yyyy-MM-dd>.md`. */
  exportFileName: string;
};

/**
 * Time-awareness settings. Persisted as `Configuration.workAwareness`.
 *
 * The default work apps depend on the OS: bundle IDs on macOS (as in 1.14.2), executable file
 * names on Windows. Decoding keeps whatever list was stored.
 */
export type WorkAwarenessPreferences = {
  idleEnabled: boolean;
  lockEnabled: boolean;
  /** Valid range 1–120. */
  idleMinutes: number;
  forgottenEnabled: boolean;
  /** Valid range 1–120. */
  forgottenMinutes: number;
  workAppIds: Array<string>;
};

export type WorkItem = {
  id: number;
  title: string;
  teamProject?: string | null;
  type?: string | null;
  workItemLink?: string | null;
};

export type WorkLog = {
  id: string;
  timestamp: string;
  length: number;
  workItemId?: number | null;
  comment?: string | null;
  activityType?: ActivityType | null;
  isCanEdit?: boolean | null;
  editedTimestamp?: string | null;
  billableLength?: number | null;
  isCanDelete?: boolean | null;
  user?: WorkLogUser | null;
};

/**
 * One change in the recovery journal (`time-edit-history.json`). Ported from `WorkLogChange`.
 *
 * Decodes the Swift journal directly: Swift's `JSONEncoder` dates (seconds since 2001), uppercase
 * UUIDs, omitted `undoOf`. Missing keys with a Swift default (`status`, `detail`) and missing
 * lists decode to those defaults instead of failing the whole journal.
 */
export type WorkLogChange = {
  id: string;
  date: string;
  /** The workspace identity (lower-cased 7pace URL) the change was made in. */
  workspace: string;
  title: string;
  /** The entries as they were before the change. */
  before: Array<WorkLog>;
  /** The entries as last confirmed by 7pace, updated after every step. */
  after: Array<WorkLog>;
  desired: Array<WorkLogDraft>;
  status: WorkLogChangeStatus;
  detail: string;
  undoOf?: string | null;
};

/** Journal state of a change. Encodes as the Swift case name (`"needsReview"`). */
export type WorkLogChangeStatus = "applying" | "complete" | "needsReview" | "reviewed" | "undone";

/** Another entry (or the running timer) that shares time with a proposed edit. */
export type WorkLogConflict = {
  id: string;
  ticketId: number | null;
  title: string;
  start: string;
  end: string;
  /** The running 7pace timer, counted as `[start, now]`. */
  active: boolean;
  /** Shared seconds. */
  overlap: number;
};

/**
 * The desired state of one worklog. Ported from `WorkLogDraft`.
 *
 * Persisted inside the edit journal. Writes use camelCase keys; reads also accept the Swift keys
 * (`existingID`, `ticketID`, …) and the Swift date format, so 1.14.x journals decode directly.
 */
export type WorkLogDraft = {
  /** The server entry this draft replaces, when it updates an existing log. */
  existingId?: string | null;
  /** For undo: the deleted ID this draft recreates (checked to be gone first). */
  restoredId?: string | null;
  start: string;
  seconds: number;
  billableSeconds: number;
  ticketId?: number | null;
  comment?: string | null;
  activityId?: string | null;
  userId?: string | null;
  allowDefaultActivity: boolean;
};

/** The fresh entry and overlap advice for a proposed edit. */
export type WorkLogEditReview = {
  /** The entry as 7pace returned it during the review. */
  original: WorkLog;
  edit: WorkLogTimeEdit;
  conflicts: Array<WorkLogConflict>;
  /** Why the advisory overlap check is incomplete; never blocks saving. */
  overlapIssue: string | null;
};

/**
 * The entries a change starts from and the drafts it should leave behind. Ported from
 * `WorkLogPlan`.
 */
export type WorkLogPlan = {
  title: string;
  before: Array<WorkLog>;
  desired: Array<WorkLogDraft>;
  /** The journal record this plan reverts. */
  undoOf?: string | null;
};

/** A start/end pair rounded to whole seconds. Ported from `WorkLogTimeEdit`. */
export type WorkLogTimeEdit = { start: string; end: string };

export type WorkLogUser = { id?: string | null };

/**
 * The user's working-time schedule. Persisted in the configuration as Swift wrote it.
 *
 * Settings written before per-weekday schedules have only `weeklyHours` and `dailyHours`; they
 * keep working (`dailyHours` Monday to Friday) and convert to `hoursByWeekday` on the first
 * [`WorkTargets::set_hours`].
 */
export type WorkTargets = {
  weeklyHours: number;
  dailyHours: number;
  /** Sunday first, matching Swift weekday numbers (index 0 = Sunday). */
  hoursByWeekday?: Array<number> | null;
  belgianHolidaysEnabled?: boolean | null;
  dateExceptions?: Array<TargetException> | null;
};
