//! Generates `apps/desktop/src/ipc/generated.ts`: the TypeScript mirror of every type the UI
//! receives (slices, intent results, errors) or sends (intents), derived from the serde types
//! with `ts-rs`. The hand-written `contract.ts` next to it maps slice names and intents onto
//! these types.
//!
//! `cargo test -p att-engine --features ts --test contract_ts` fails when the file is out of date;
//! `UPDATE_CONTRACT=1 cargo test -p att-engine --features ts --test contract_ts` rewrites it.

#![cfg(feature = "ts")]

use std::collections::BTreeMap;
use std::path::PathBuf;

use ts_rs::{Config, TS, TypeVisitor};

use att_engine::controllers::ControllerIntent;
use att_engine::controllers::view as controllers;
use att_engine::intent::GenericIntent;
use att_engine::ipc::IpcError;
use att_engine::session::SessionIntent;
use att_engine::session::view as session;

/// Collects the declarations of a type and everything it refers to, once per TypeScript name.
struct Collector {
    cfg: Config,
    /// TypeScript name → (Rust type name, declaration).
    decls: BTreeMap<String, (String, String)>,
}

impl TypeVisitor for Collector {
    fn visit<T: TS + 'static + ?Sized>(&mut self) {
        // Primitives and wrappers (`Option`, `Vec`, maps, `Box`, `Arc`) have no declaration of
        // their own; their type arguments are visited separately.
        if T::output_path().is_none() {
            T::visit_generics(self);
            return;
        }
        let name = T::ident(&self.cfg);
        let rust = std::any::type_name::<T>();
        let rust = rust.split('<').next().unwrap_or(rust).to_string();
        if let Some((existing, _)) = self.decls.get(&name) {
            assert_eq!(
                existing, &rust,
                "two Rust types export as `{name}`; give one a #[ts(rename = \"…\")]"
            );
            return;
        }
        let decl = pretty::declaration(T::docs().as_deref(), &T::decl(&self.cfg));
        self.decls.insert(name, (rust, decl));
        T::visit_dependencies(self);
        T::visit_generics(self);
    }
}

fn generate() -> String {
    let mut collector =
        Collector { cfg: Config::new().with_large_int("number"), decls: BTreeMap::new() };
    let c = &mut collector;
    // Intents and errors.
    c.visit::<GenericIntent>();
    c.visit::<SessionIntent>();
    c.visit::<ControllerIntent>();
    c.visit::<IpcError>();
    // Session slices (`workItems` is a map of `WorkItem`, declared in contract.ts).
    c.visit::<session::AppSlice>();
    c.visit::<att_core::interface_prefs::InterfacePreferences>();
    c.visit::<session::ConnectionSlice>();
    c.visit::<session::TrackingSlice>();
    c.visit::<session::FlowSlice>();
    c.visit::<session::PromptsSlice>();
    c.visit::<session::ProgressSlice>();
    c.visit::<session::HistorySlice>();
    c.visit::<att_core::model::WorkItem>();
    c.visit::<session::RepositoriesSlice>();
    c.visit::<session::AgendaSlice>();
    c.visit::<session::SettingsSlice>();
    c.visit::<session::FigmaSlice>();
    // Controller slices and results.
    c.visit::<controllers::StatisticsSlice>();
    c.visit::<controllers::EntriesPage>();
    c.visit::<controllers::TimeEditorSlice>();
    c.visit::<controllers::DayReviewSlice>();
    c.visit::<controllers::WeeklySlice>();
    c.visit::<controllers::OfflineSlice>();
    c.visit::<controllers::TicketContextSlice>();

    let mut out = String::from(
        "// Generated by crates/att-engine/tests/contract_ts.rs from the Rust contract types.\n\
         // Do not edit: run `npm run contract` in apps/desktop (or the cargo command in that\n\
         // file) after changing a Rust type. Instants are RFC 3339 strings, days `YYYY-MM-DD`.\n\n",
    );
    for (_, (_, decl)) in collector.decls {
        out.push_str(&decl);
        out.push_str("\n\n");
    }
    out.truncate(out.trim_end().len());
    out.push('\n');
    out
}

/// Defaults the UI fixtures start from (macOS defaults, so the file is the same on every OS).
fn defaults() -> String {
    let configuration = att_core::Configuration {
        awareness: att_core::awareness::WorkAwarenessPreferences::default_for(
            att_core::model::HostOs::Macos,
        ),
        ..att_core::Configuration::default()
    };
    let value = serde_json::json!({ "configuration": configuration });
    let mut text = serde_json::to_string_pretty(&value).expect("defaults serialize");
    text.push('\n');
    text
}

fn ipc_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../apps/desktop/src/ipc")
}

/// Writes `contents` with `UPDATE_CONTRACT` set, otherwise fails when the file differs.
fn check(relative: &str, contents: &str) {
    let path = ipc_dir().join(relative);
    if std::env::var_os("UPDATE_CONTRACT").is_some() {
        std::fs::create_dir_all(path.parent().expect("parent")).expect("create the folder");
        std::fs::write(&path, contents).expect("write the generated file");
        return;
    }
    // Line endings may differ in a Windows checkout.
    let current = std::fs::read_to_string(&path).unwrap_or_default().replace("\r\n", "\n");
    assert!(
        current == contents,
        "{} is out of date: run `UPDATE_CONTRACT=1 cargo test -p att-engine --features ts --test contract_ts`",
        path.display()
    );
}

#[test]
fn typescript_contract_is_up_to_date() {
    check("generated.ts", &generate());
}

#[test]
fn fixture_defaults_are_up_to_date() {
    check("fixtures/defaults.json", &defaults());
}

/// A small pretty-printer for the TypeScript subset ts-rs emits (object types, unions,
/// intersections, generics, tuples, literals and JSDoc comments), so the generated file reads
/// like hand-written code: short types on one line, long ones one member or variant per line.
mod pretty {
    const WIDTH: usize = 100;

    #[derive(Clone, Debug, PartialEq)]
    enum Tok {
        Comment(Vec<String>),
        Str(String),
        Word(String),
        P(char),
    }

    #[derive(Debug)]
    enum Ty {
        Union(Vec<Ty>),
        Inter(Vec<Ty>),
        Object(Vec<Member>),
        Tuple(Vec<Ty>),
        Ref(String, Vec<Ty>),
        Lit(String),
        Paren(Box<Ty>),
    }

    #[derive(Debug)]
    struct Member {
        docs: Vec<String>,
        key: Key,
        optional: bool,
        ty: Ty,
    }

    #[derive(Debug)]
    enum Key {
        Name(String),
        Index(String, Ty),
    }

    fn comment_lines(text: &str) -> Vec<String> {
        let body = text.trim().trim_start_matches("/**").trim_end_matches("*/");
        let mut lines: Vec<String> = body
            .lines()
            .map(|line| {
                let line = line.trim();
                let line = line.strip_prefix('*').unwrap_or(line);
                line.strip_prefix(' ').unwrap_or(line).trim_end().to_string()
            })
            .collect();
        while lines.first().is_some_and(String::is_empty) {
            lines.remove(0);
        }
        while lines.last().is_some_and(String::is_empty) {
            lines.pop();
        }
        lines
    }

    fn tokenize(source: &str) -> Vec<Tok> {
        let chars: Vec<char> = source.chars().collect();
        let mut tokens = Vec::new();
        let mut i = 0;
        while i < chars.len() {
            let c = chars[i];
            if c.is_whitespace() {
                i += 1;
            } else if c == '/' && chars.get(i + 1) == Some(&'*') {
                let start = i;
                i += 2;
                while i + 1 < chars.len() && !(chars[i] == '*' && chars[i + 1] == '/') {
                    i += 1;
                }
                i += 2;
                let text: String = chars[start..i.min(chars.len())].iter().collect();
                tokens.push(Tok::Comment(comment_lines(&text)));
            } else if c == '"' {
                let start = i;
                i += 1;
                while i < chars.len() && chars[i] != '"' {
                    if chars[i] == '\\' {
                        i += 1;
                    }
                    i += 1;
                }
                i += 1;
                tokens.push(Tok::Str(chars[start..i].iter().collect()));
            } else if "{}[]<>(),;|&:?=".contains(c) {
                tokens.push(Tok::P(c));
                i += 1;
            } else {
                let start = i;
                while i < chars.len()
                    && !chars[i].is_whitespace()
                    && !"{}[]<>(),;|&:?=\"".contains(chars[i])
                {
                    i += 1;
                }
                tokens.push(Tok::Word(chars[start..i].iter().collect()));
            }
        }
        tokens
    }

    struct Parser {
        tokens: Vec<Tok>,
        at: usize,
    }

    impl Parser {
        fn peek(&self) -> Option<&Tok> {
            self.tokens.get(self.at)
        }
        fn next(&mut self) -> Tok {
            let token = self.tokens[self.at].clone();
            self.at += 1;
            token
        }
        fn eat(&mut self, c: char) -> bool {
            if self.peek() == Some(&Tok::P(c)) {
                self.at += 1;
                true
            } else {
                false
            }
        }
        fn expect(&mut self, c: char) {
            assert!(self.eat(c), "expected `{c}` at token {} of {:?}", self.at, self.tokens);
        }
        fn ty(&mut self) -> Ty {
            self.eat('|');
            let mut parts = vec![self.inter()];
            while self.eat('|') {
                parts.push(self.inter());
            }
            if parts.len() == 1 { parts.pop().unwrap() } else { Ty::Union(parts) }
        }
        fn inter(&mut self) -> Ty {
            let mut parts = vec![self.primary()];
            while self.eat('&') {
                parts.push(self.primary());
            }
            if parts.len() == 1 { parts.pop().unwrap() } else { Ty::Inter(parts) }
        }
        fn primary(&mut self) -> Ty {
            match self.next() {
                Tok::P('{') => self.object(),
                Tok::P('[') => {
                    let mut items = Vec::new();
                    while !self.eat(']') {
                        items.push(self.ty());
                        self.eat(',');
                    }
                    Ty::Tuple(items)
                }
                Tok::P('(') => {
                    let inner = self.ty();
                    self.expect(')');
                    Ty::Paren(Box::new(inner))
                }
                Tok::Str(text) => Ty::Lit(text),
                Tok::Word(word) => {
                    let mut args = Vec::new();
                    if self.eat('<') {
                        while !self.eat('>') {
                            args.push(self.ty());
                            self.eat(',');
                        }
                    }
                    if args.is_empty() { Ty::Lit(word) } else { Ty::Ref(word, args) }
                }
                other => panic!("unexpected {other:?} at token {}", self.at),
            }
        }
        fn object(&mut self) -> Ty {
            let mut members = Vec::new();
            loop {
                let mut docs = Vec::new();
                while let Some(Tok::Comment(lines)) = self.peek().cloned() {
                    self.at += 1;
                    docs.extend(lines);
                }
                if self.eat('}') {
                    break;
                }
                let key = match self.next() {
                    Tok::P('[') => {
                        let Tok::Word(var) = self.next() else { panic!("index key") };
                        let Tok::Word(_in) = self.next() else { panic!("`in`") };
                        let of = self.ty();
                        self.expect(']');
                        Key::Index(var, of)
                    }
                    Tok::Word(name) => Key::Name(name),
                    Tok::Str(name) => {
                        let bare = &name[1..name.len() - 1];
                        let identifier = !bare.is_empty()
                            && bare
                                .chars()
                                .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '$')
                            && !bare.starts_with(|c: char| c.is_ascii_digit());
                        Key::Name(if identifier { bare.to_string() } else { name })
                    }
                    other => panic!("unexpected key {other:?}"),
                };
                let optional = self.eat('?');
                self.expect(':');
                let ty = self.ty();
                if !self.eat(',') {
                    self.eat(';');
                }
                members.push(Member { docs, key, optional, ty });
            }
            Ty::Object(members)
        }
    }

    fn has_docs(ty: &Ty) -> bool {
        match ty {
            Ty::Object(members) => members.iter().any(|m| !m.docs.is_empty() || has_docs(&m.ty)),
            Ty::Union(parts) | Ty::Inter(parts) | Ty::Tuple(parts) | Ty::Ref(_, parts) => {
                parts.iter().any(has_docs)
            }
            Ty::Paren(inner) => has_docs(inner),
            Ty::Lit(_) => false,
        }
    }

    fn key_text(key: &Key) -> String {
        match key {
            Key::Name(name) => name.clone(),
            Key::Index(var, of) => format!("[{var} in {}]", inline(of)),
        }
    }

    fn inline(ty: &Ty) -> String {
        match ty {
            Ty::Union(parts) => parts.iter().map(inline).collect::<Vec<_>>().join(" | "),
            Ty::Inter(parts) => parts.iter().map(inline).collect::<Vec<_>>().join(" & "),
            Ty::Object(members) if members.is_empty() => "{}".into(),
            Ty::Object(members) => format!(
                "{{ {} }}",
                members
                    .iter()
                    .map(|m| format!(
                        "{}{}: {}",
                        key_text(&m.key),
                        if m.optional { "?" } else { "" },
                        inline(&m.ty)
                    ))
                    .collect::<Vec<_>>()
                    .join("; ")
            ),
            Ty::Tuple(items) => {
                format!("[{}]", items.iter().map(inline).collect::<Vec<_>>().join(", "))
            }
            Ty::Ref(name, args) => {
                format!("{name}<{}>", args.iter().map(inline).collect::<Vec<_>>().join(", "))
            }
            Ty::Lit(text) => text.clone(),
            Ty::Paren(inner) => format!("({})", inline(inner)),
        }
    }

    fn docs_block(lines: &[String], indent: &str) -> String {
        match lines {
            [] => String::new(),
            [line] => format!("{indent}/** {line} */\n"),
            lines => {
                let mut out = format!("{indent}/**\n");
                for line in lines {
                    if line.is_empty() {
                        out.push_str(&format!("{indent} *\n"));
                    } else {
                        out.push_str(&format!("{indent} * {line}\n"));
                    }
                }
                out.push_str(&format!("{indent} */\n"));
                out
            }
        }
    }

    /// Renders `ty` starting at column `column` on a line indented by `indent` spaces.
    fn print(ty: &Ty, indent: usize, column: usize) -> String {
        let flat = inline(ty);
        if !has_docs(ty) && column + flat.len() <= WIDTH {
            return flat;
        }
        let pad = " ".repeat(indent);
        match ty {
            Ty::Object(members) => {
                let inner = " ".repeat(indent + 2);
                let mut out = String::from("{\n");
                for m in members {
                    out.push_str(&docs_block(&m.docs, &inner));
                    let head = format!(
                        "{inner}{}{}: ",
                        key_text(&m.key),
                        if m.optional { "?" } else { "" }
                    );
                    let body = print(&m.ty, indent + 2, head.len());
                    out.push_str(&format!("{head}{body};\n"));
                }
                out.push_str(&format!("{pad}}}"));
                out
            }
            Ty::Union(parts) => {
                let mut out = String::new();
                for part in parts {
                    out.push_str(&format!("\n{pad}  | {}", print(part, indent + 4, indent + 4)));
                }
                out
            }
            Ty::Inter(parts) => {
                parts.iter().map(|part| print(part, indent, column)).collect::<Vec<_>>().join(" & ")
            }
            Ty::Ref(name, args) => format!(
                "{name}<{}>",
                args.iter()
                    .map(|arg| print(arg, indent, column + name.len() + 1))
                    .collect::<Vec<_>>()
                    .join(", ")
            ),
            Ty::Tuple(items) => format!(
                "[{}]",
                items
                    .iter()
                    .map(|item| print(item, indent, column + 1))
                    .collect::<Vec<_>>()
                    .join(", ")
            ),
            Ty::Paren(inner) => format!("({})", print(inner, indent, column + 1)),
            Ty::Lit(text) => text.clone(),
        }
    }

    /// `docs` as ts-rs returns them and `decl` = `type Name = …;`.
    pub fn declaration(docs: Option<&str>, decl: &str) -> String {
        let decl = decl.trim().strip_prefix("type ").expect("a type declaration");
        let (name, body) = decl.split_once(" = ").expect("`=` in the declaration");
        let body = body.trim().trim_end_matches(';');
        let mut parser = Parser { tokens: tokenize(body), at: 0 };
        let ty = parser.ty();
        assert_eq!(parser.at, parser.tokens.len(), "unparsed tail in {name}: {body}");
        let mut out = docs.map(|docs| docs_block(&comment_lines(docs), "")).unwrap_or_default();
        let head = format!("export type {name} = ");
        let printed = print(&ty, 0, head.len());
        if printed.starts_with('\n') {
            out.push_str(head.trim_end());
        } else {
            out.push_str(&head);
        }
        out.push_str(&printed);
        out.push(';');
        out
    }
}
