//! Interoperability with the real Tauri CLI signer, in both directions, using throwaway keys in a
//! temporary folder. It downloads `@tauri-apps/cli@2` with npx, so it is ignored by default:
//! `cargo test -p att-release --test tauri_interop -- --ignored`.

use std::fs;
use std::path::Path;
use std::process::Command;

use att_release::updater_key::{self, KeySource};

fn npx(args: &[&str], dir: &Path) {
    let program = if cfg!(windows) { "npx.cmd" } else { "npx" };
    let output = Command::new(program)
        .args(["--yes", "@tauri-apps/cli@2", "signer"])
        .args(args)
        .current_dir(dir)
        .env("CI", "true")
        .env_remove("TAURI_SIGNING_PRIVATE_KEY")
        .env_remove("TAURI_SIGNING_PRIVATE_KEY_PATH")
        .env_remove("TAURI_SIGNING_PRIVATE_KEY_PASSWORD")
        .output()
        .expect("npx is required");
    assert!(
        output.status.success(),
        "tauri signer {args:?} failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
}

#[test]
#[ignore = "downloads @tauri-apps/cli@2 with npx"]
fn keys_and_signatures_interoperate_with_the_tauri_cli() {
    let temp = tempfile::tempdir().unwrap();
    let data = b"updater archive bytes";

    // A key generated by `tauri signer generate` signs with this tool and verifies like the plugin.
    let tauri_key = temp.path().join("tauri.key");
    npx(&["generate", "--ci", "-p", "", "-w", tauri_key.to_str().unwrap()], temp.path());
    let key = updater_key::load(&KeySource::File(tauri_key.clone()), "", None).unwrap();
    assert_eq!(
        key.public_b64,
        fs::read_to_string(updater_key::public_path(&tauri_key)).unwrap().trim()
    );
    let signature = updater_key::sign_bytes(
        &key,
        data,
        "Azure-timetracker-2.0.0-universal.app.tar.gz",
        "2.0.0",
    )
    .unwrap();
    updater_key::verify(data, &signature, &key.public_b64, Some("2.0.0")).unwrap();

    // A key from `keygen` signs with `tauri signer sign --app-version`, and the result verifies here.
    let ours = temp.path().join("ours.key");
    let (_, public) = updater_key::keygen(&ours, "", None).unwrap();
    let file = temp.path().join("Azure-timetracker-2.0.0-x64-setup.exe");
    fs::write(&file, data).unwrap();
    npx(
        &[
            "sign",
            "-f",
            ours.to_str().unwrap(),
            "-p",
            "",
            "--app-version",
            "2.0.0",
            file.to_str().unwrap(),
        ],
        temp.path(),
    );
    let tauri_signature =
        fs::read_to_string(temp.path().join("Azure-timetracker-2.0.0-x64-setup.exe.sig")).unwrap();
    let comment =
        updater_key::verify(data, tauri_signature.trim(), &public, Some("2.0.0")).unwrap();
    assert!(comment.ends_with("\tversion:2.0.0"), "{comment}");
}
